include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    avoid_positional_boolean_parameters: false
    no_default_cases: false

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**.g.dart'