name: {{name.snakeCase()}}_app_ui
description: UI Toolkit for the {{name.titleCase()}} Flutter Application
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  very_good_analysis: ^4.0.0+1

flutter_gen:
  output: lib/src/gen

flutter:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/audios/
    - assets/videos/
    - assets/rive/
    - assets/lottie/
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/NunitoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/NunitoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/NunitoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/NunitoSans-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/NunitoSans-BlackItalic.ttf
          weight: 900
          style: italic
