name: {{name}}
description: {{description}}

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  {{name.snakeCase()}}_ui:
    path: packages/{{name.snakeCase()}}_ui
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  fluttertoast: ^8.2.2
  shimmer: ^3.0.0
  styled_text: ^7.0.0
  go_router: ^9.0.0

dev_dependencies:
  custom_lint: ^0.4.0
  dart_code_metrics: ^5.7.4
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - packages/{{name.snakeCase()}}_ui/assets/
